version: '3.7'

services:
  web:
    container_name: exam-marking_web
    build:
      context: ./web
      dockerfile: Dockerfile
#    env_file: .env
    volumes:
      - './web:/app/web'
      - './web/node_modules:/app/web/node_modules'
    ports:
      - '1000:1000'
    command: [ "npm", "run", "dev", '--', '--port', '1000' ]

