version: '3.7'

services:
  web:
    container_name: wedding_web_main
    build:
      context: ./web
      dockerfile: Dockerfile
#    env_file: .env
    volumes:
      - './web:/app/web'
      - './web/node_modules:/app/web/node_modules'
    ports:
      - '1000:3000'
    command: ['node', '.output/server/index.mjs']

